### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by damayantibaihaqi** [kelvins/steganography#9]
Traceback (most recent call last):
  File "steganography.py", line 155, in <module>
    cli()
  File "/home/bambang/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/bambang/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/bambang/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bambang/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bambang/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "steganography.py", line 150, in unmerge
    unmerged_image = Steganography.unmerge(Image.open(img))
  File "steganography.py", line 110, in unmerge
    r, g, b = Steganography.__int_to_bin(pixel_map[i, j])
  File "steganography.py", line 17, in __int_to_bin
    r, g, b = rgb
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by kelvins** [comment]
Which image format are you trying to use?

**Comment by prophet6250** [comment]
@kelvins I'm encountering the same issue, and currently using the jpg format. I know you mentioned in another issue that we should use png, but care to explain a little as to why this is happening?

**Comment by Slmslmslmslm** [comment]
@prophet6250 I would imagine it has to do with the encoding/decoding of the file formats. The program handles a particular file format and data structure, adding compatibility would be possible, but would require exception handling, and conversion of .png to .jpg before embedding anything.

"ValueError: not enough values to unpack (expected 3, got 2)" tells us the expected minimum values weren't given, probably due to the difference in file formats, but the ValueError error handler can be used for the exception handling, file conversion if the error occurs, and the format of the file determined.

Also, "r, g, b = rgb" is the value it's trying to assign, but it's only received two values.
